apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hres7q867-dotnet-basic
  janus-idp.io/tekton: hres7q867-dotnet-basic
  backstage.io/kubernetes-id: hres7q867-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hres7q867-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
